### ISSUE TITLE
Helper/Validator Text

### ISSUE THREAD

**Issue by kiranvenkatesh** [jspears/subschema#15]
Currently the helper/validator use the same DOM element to render text. Can these be separated? This would be something very useful.

Can I also build the application to test my changes?

**Comment by jspears** [comment]
yes, I'll do that.   if you have something working send  a PR, otherwise it may be a little time.

You should be able to run 
```sh
 npm run build-demo
```
let me know if this doesn't work.

**Comment by kiranvenkatesh** [comment]
I submitted a pull request. Hoping I went through the right process. I attached an image of what I wanted to acheive.

Also I would like to create a custom version of subschema for use in our projects and had some questions. Let me know if I can post them here. Thanks!

**Comment by kiranvenkatesh** [comment]
I see that "npm test" on my branch that I forked from master failed at "npm test".

Firefox 40.0.0 (Mac OS X 10.10.0) ERROR
  ReferenceError: require is not defined
  at /Users/kvrangul/kno/subschema/test/index.js:1

Any specific config changes to be made?

**Comment by jspears** [comment]
Did u run npm install first?

**Comment by kiranvenkatesh** [comment]
I did. Removed node modules just to be sure and ran install followed by npm test.

WARN [preprocess]: Can not load "webpack"!
  TypeError: undefined is not a function
    at Plugin.notifyKarmaAboutChanges (/Users/kvrangul/kno/subschema/node_modules/karma-webpack/index.js:108:15)
    at Plugin.<anonymous> (/Users/kvrangul/kno/subschema/node_modules/karma-webpack/index.js:72:9)
    at Tapable.applyPlugins (/Users/kvrangul/kno/subschema/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/kvrangul/kno/subschema/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/kvrangul/kno/subschema/node_modules/webpack/lib/Compiler.js:61:18)
    at Tapable.emitRecords (/Users/kvrangul/kno/subschema/node_modules/webpack/lib/Compiler.js:281:37)
    at Watching.<anonymous> (/Users/kvrangul/kno/subschema/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/kvrangul/kno/subschema/node_modules/webpack/lib/Compiler.js:274:11
    at Tapable.applyPluginsAsync (/Users/kvrangul/kno/subschema/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/Users/kvrangul/kno/subschema/node_modules/webpack/lib/Compiler.js:271:8)
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Firefox
INFO [Firefox 40.0.0 (Mac OS X 10.10.0)]: Connected on socket 1e8OvBqmrZSVXd_9I0gn with id 43120618
Firefox 40.0.0 (Mac OS X 10.10.0) ERROR
  ReferenceError: require is not defined
  at /Users/kvrangul/kno/subschema/test/index.js:1
Firefox 40.0.0 (Mac OS X 10.10.0): Executed 0 of 0 ERROR (0.187 secs / 0 secs)

**Comment by jspears** [comment]
Closing this unless, you are still seeing it.  I believe it was an issue with karma's webpack plugin that has been resolved.
